In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5,12,7]], columns=['cgpa', 'resumeScore', 'lpa'])

In [3]:
df

cgpa  resumeScore  lpa
0     8            8    4
1     7            9    5
2     6           10    6
3     5           12    7

In [4]:
def initialiseParameters(layerDimensions):
    params = {}
    L = len(layerDimensions)
    for i in range(1, L):
        params['W'+str(i)] = np.ones((layerDimensions[i-1], layerDimensions[i]))*0.1
        params['b' + str(i)] = np.zeros((layerDimensions[i], 1))
    return params

In [5]:
initialiseParameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [6]:
def linearForward(A_prev, W, b):
    Z = np.dot(W.T, A_prev) + b
    return Z

In [7]:
# main Forward propogation function
def LLayerForward(X, params):
    A = X
    L = len(params)//2
    for l in range(1, L+1):
        A_prev = A
        Wl = params['W'+str(l)]
        bl = params['b'+str(l)]
        print('A'+str(l-1)+': ', A_prev)
        print('W'+str(l)+': ', Wl)
        print('b'+str(l)+': ', bl)
        print('-'*40)
        A = linearForward(A_prev, Wl, bl)
        print('A'+str(l)+': ', A)
        print('*'*40)
    return A, A_prev

In [8]:
X = df[['cgpa', 'resumeScore']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

In [9]:
params = initialiseParameters([2,2,1])
y_hat, A1 = LLayerForward(X, params)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [10]:
y_hat = y_hat[0][0]
(y-y_hat)**2

13.542399999999997

In [11]:
def updateParams(params, y, y_hat, A1, X, lr):
    # W2 n b2:
    params['W2'][0][0] = params['W2'][0][0] + lr*(2*(y-y_hat)*A1[0][0])
    params['W2'][1][0] = params['W2'][1][0] + lr*(2*(y-y_hat)*A1[1][0])
    params['b2'][0][0] = params['b2'][0][0] + lr*(2*(y-y_hat))
    # W1 n b1:
    params['W1'][0][0] = params['W1'][0][0] + lr*(2*(y-y_hat)*params['W2'][0][0]*X[0][0])
    params['W1'][0][1] = params['W1'][0][1] + lr*(2*(y-y_hat)*params['W2'][0][0]*X[1][0])
    params['b1'][0][0] = params['b1'][0][0] + lr*(2*(y-y_hat)*params['W2'][0][0])
    
    params['W1'][1][0] = params['W1'][1][0] + lr*(2*(y-y_hat)*params['W2'][1][0]*X[0][0])
    params['W1'][1][1] = params['W1'][1][1] + lr*(2*(y-y_hat)*params['W2'][1][0]*X[1][0])
    params['b1'][1][0] = params['b1'][1][0] + lr*(2*(y-y_hat)*params['W2'][1][0])
    return params


In [12]:
params = updateParams(params, y, y_hat, A1, X, 0.001)
params

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [13]:
# the final implementation
def myNN():
    result = []
    params = initialiseParameters([2,2,1])
    epochs = 5
    for i in range(epochs):
        print('='*50)
        loss = []
        for j in range(df.shape[0]):
            X = df[['cgpa', 'resumeScore']].values[j].reshape(2,1)
            y = df[['lpa']].values[j][0]
            y_hat, A1 = LLayerForward(X, params)
            y_hat = y_hat[0][0]
            params = updateParams(params, y, y_hat, A1, X, 0.001)
            loss.append((y-y_hat)**2)
        print(f'Epoch: {i+1}, Loss: {np.array(loss).mean()}')
        result.append(f'Epoch: {i+1}, Loss: {np.array(loss).mean()}')
        print('='*50)
    return result, params
res, params = myNN()        


A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.00736]]
----------------------------------------
A2:  [[0.38876757]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.11481311 0.11716504]
 [0.11481311 0.11716504]]
b1:  [[0.00199863]
 [0.00199863]]
----------------------------------------
A1:  [[1.83900839]
 [1.8766392 ]]
****************************************
A1:  [[1.83900839]
 [1.8766392 ]]
W2:  [[0.12751067]
 [0.12

A2:  [[2.44431656]]
****************************************
A0:  [[ 5]
 [12]]
W1:  [[0.21820284 0.2868458 ]
 [0.22413136 0.29633635]]
b1:  [[0.0187504 ]
 [0.01969946]]
----------------------------------------
A1:  [[3.79934094]
 [5.00996462]]
****************************************
A1:  [[3.79934094]
 [5.00996462]]
W2:  [[0.3162686 ]
 [0.35122387]]
b2:  [[0.09176186]]
----------------------------------------
A2:  [[3.05299325]]
****************************************
Epoch: 3, Loss: 10.139874435827522
A0:  [[8]
 [8]]
W1:  [[0.23186978 0.31964643]
 [0.23955518 0.33335352]]
b1:  [[0.02148378]
 [0.02278422]]
----------------------------------------
A1:  [[3.79288343]
 [5.24678381]]
****************************************
A1:  [[3.79288343]
 [5.24678381]]
W2:  [[0.34626065]
 [0.39077259]]
b2:  [[0.09965587]]
----------------------------------------
A2:  [[3.46328148]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.23487825 0.32265491]
 [0.2429593  0.33675764]]
b1:  [

In [14]:
for i in res:
    print(i)

Epoch: 1, Loss: 26.28249792398698
Epoch: 2, Loss: 19.438253848220803
Epoch: 3, Loss: 10.139874435827522
Epoch: 4, Loss: 3.385561305106485
Epoch: 5, Loss: 1.3198454128484567


In [15]:
print(params)

{'W1': array([[0.273603  , 0.3993222 ],
       [0.28787155, 0.42586102]]), 'b1': array([[0.02885522],
       [0.03133223]]), 'W2': array([[0.42574893],
       [0.50219328]]), 'b2': array([[0.11841278]])}


In [16]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense


In [17]:
model = Sequential()

In [18]:
model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

c:\python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.get_weights()

[array([[-0.64014065,  0.06617236],
        [-0.6089782 ,  0.47459257]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.45024335],
        [-0.87838143]], dtype=float32),
 array([0.], dtype=float32)]

In [21]:
new_weights = [np.array([[0.1,0.1], [0.1,0.1]], dtype=np.float32), 
                np.array([0.,0.], dtype=np.float32),
                np.array([[0.1], [0.1]], dtype=np.float32),
                np.array([0.], dtype=np.float32)
               ]

In [22]:
model.set_weights(new_weights)

In [23]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [24]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)


In [25]:
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [26]:
h = model.fit(df.iloc[:, 0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 31.9603
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.4197  
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31.1265  
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.0571 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.3830 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.4229 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 29.0867 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 22.1799  
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20.1839  
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.8353  
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30.1377 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19.2985 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20.2793 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.8723 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 26.0026 
Epoch 16/75
4/4

In [27]:
model.get_weights()

[array([[0.37366673, 0.37366673],
        [0.36545807, 0.36545807]], dtype=float32),
 array([0.27227923, 0.27227923], dtype=float32),
 array([[0.37286362],
        [0.37286362]], dtype=float32),
 array([0.20472567], dtype=float32)]