In [148]:
import pandas as pd
import numpy as np

In [149]:
df = pd.DataFrame([[8,8,1], [7,9,1], [6,10,0], [5,5,0]], columns=['cgpa', 'resumeScore', 'placed'])

In [150]:
df

cgpa  resumeScore  placed
0     8            8       1
1     7            9       1
2     6           10       0
3     5            5       0

In [151]:
def initialiseParameters(layerDimensions):
    params = {}
    L = len(layerDimensions)
    for i in range(1, L):
        params['W'+str(i)] = np.ones((layerDimensions[i-1], layerDimensions[i]))*0.1
        params['b' + str(i)] = np.zeros((layerDimensions[i], 1))
    return params

In [152]:
import math
def linearForward(A_prev, W, b):
    Z = np.dot(W.T, A_prev) + b
    r = 1/(1+math.e ** (-Z))
    return r

In [153]:
# main Forward propogation function
def LLayerForward(X, params):
    A = X
    L = len(params)//2
    for l in range(1, L+1):
        A_prev = A
        Wl = params['W'+str(l)]
        bl = params['b'+str(l)]
        print('A'+str(l-1)+': ', A_prev)
        print('W'+str(l)+': ', Wl)
        print('b'+str(l)+': ', bl)
        print('-'*40)
        A = linearForward(A_prev, Wl, bl)
        print('A'+str(l)+': ', A)
        print('*'*40)
    return A, A_prev

In [154]:
X = df[['cgpa', 'resumeScore']].values[0].reshape(2,1)
y = df[['placed']].values[0][0]

In [155]:
params = initialiseParameters([2,2,1])
y_hat, A1 = LLayerForward(X, params)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1:  [[0.83201839]
 [0.83201839]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************


In [156]:
y_hat = y_hat[0][0]
y_hat

0.5415051895671072

In [157]:
loss = -y*np.log(y_hat)-(1-y)*np.log(1-y_hat)
loss

0.613402628898913

In [158]:
def updateParams(params, y, y_hat, A1, X, lr):
    # W2 n b2:
    params['W2'][0][0] = params['W2'][0][0] + lr*((y-y_hat)*A1[0][0])
    params['W2'][1][0] = params['W2'][1][0] + lr*((y-y_hat)*A1[1][0])
    params['b2'][0][0] = params['b2'][0][0] + lr*((y-y_hat))
    # W1 n b1    
    params['W1'][0][0] = params['W1'][0][0] + lr*((y-y_hat)*params['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
    params['W1'][0][1] = params['W1'][0][1] + lr*((y-y_hat)*params['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
    params['b1'][0][0] = params['b1'][0][0] + lr*((y-y_hat)*params['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

    params['W1'][1][0] = params['W1'][1][0] + lr*((y-y_hat)*params['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
    params['W1'][1][1] = params['W1'][1][1] + lr*((y-y_hat)*params['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
    params['b1'][1][0] = params['b1'][1][0] + lr*((y-y_hat)*params['W2'][1][0]*A1[1][0]*(1-A1[1][0]))
    return params


In [159]:
params = updateParams(params, y, y_hat, A1, X, 0.001)
params

{'W1': array([[0.10005146, 0.10005146],
        [0.10005146, 0.10005146]]),
 'b1': array([[6.43254269e-06],
        [6.43254269e-06]]),
 'W2': array([[0.10038148],
        [0.10038148]]),
 'b2': array([[0.00045849]])}

In [160]:
# the final implementation
def myNN():
    result = []
    params = initialiseParameters([2,2,1])
    epochs = 5
    for i in range(epochs):
        print('='*50)
        loss = []
        for j in range(df.shape[0]):
            X = df[['cgpa', 'resumeScore']].values[j].reshape(2,1)
            y = df[['placed']].values[j][0]
            y_hat, A1 = LLayerForward(X, params)
            y_hat = y_hat[0][0]
            params = updateParams(params, y, y_hat, A1, X, 0.001)
            loss.append(-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))
        print(f'Epoch: {i+1}, Loss: { -y*np.log(y_hat)-(1-y)*np.log(1-y_hat)}')
        result.append(f'Epoch: {i+1}, Loss: { -y*np.log(y_hat)-(1-y)*np.log(1-y_hat)}')
        print('='*50)
    return result, params
res, params = myNN()        


A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1:  [[0.83201839]
 [0.83201839]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10005146 0.10005146]
 [0.10005146 0.10005146]]
b1:  [[6.43254269e-06]
 [6.43254269e-06]]
----------------------------------------
A1:  [[0.83213433]
 [0.83213433]]
****************************************
A1:  [[0.83213433]
 [0.83213433]]
W2:  [[0.10038148]
 [0.10038148]]
b2:  [[0.00045849]]
----------------------------------------
A2:  [[0.54178239]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.10009661 0.10010951]
 [0.10009661 0.10010951]]
b1:  [[1.28820601e-05]
 [1.28820601e-05]]
----------------------------------------
A1:  [[0.83223611]
 [0.83226492]]
****************************************
A1

In [161]:
for i in res:
    print(i)
params

Epoch: 1, Loss: 0.7693775060589632
Epoch: 2, Loss: 0.7692251192515712
Epoch: 3, Loss: 0.7690731117472573
Epoch: 4, Loss: 0.7689214825009097
Epoch: 5, Loss: 0.7687702304707567


{'W1': array([[0.09999206, 0.09990492],
        [0.09999213, 0.09990497]]),
 'b1': array([[-2.61664510e-05],
        [-2.61642051e-05]]),
 'W2': array([[0.09959859],
        [0.09959864]]),
 'b2': array([[-0.00080729]])}

In [162]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense


In [163]:
model = Sequential()

In [164]:
model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

c:\python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [165]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [166]:
model.get_weights()

[array([[ 0.14973593,  1.0344151 ],
        [-0.7065031 ,  1.216582  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.03506041],
        [0.6382669 ]], dtype=float32),
 array([0.], dtype=float32)]

In [167]:
new_weights = [np.array([[0.1,0.1], [0.1,0.1]], dtype=np.float32), 
                np.array([0.,0.], dtype=np.float32),
                np.array([[0.1], [0.1]], dtype=np.float32),
                np.array([0.], dtype=np.float32)
               ]

In [168]:
model.set_weights(new_weights)

In [169]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [170]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)


In [171]:
model.compile(loss='binary_crossentropy', optimizer=optimizer)

In [172]:
h = model.fit(df.iloc[:, 0:-1].values, df['placed'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.7173
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6721 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7317 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7128 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6829  
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7307 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6725 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7020  
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7282 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7121 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7120 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6591 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7276 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6831 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7053 
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━

In [173]:
model.get_weights()

[array([[0.10225239, 0.10225239],
        [0.08044203, 0.08044203]], dtype=float32),
 array([-0.04450627, -0.04450627], dtype=float32),
 array([[0.08852869],
        [0.08852869]], dtype=float32),
 array([-0.0210135], dtype=float32)]